services:
  rice-streamlit:
    build: .
    container_name: rice_streamlit
    restart: always
    ports:
      - "443:8501"
    command: streamlit run app.py --server.address=0.0.0.0 --server.port=8501
